name: bl-seti-cloud
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - tensorflow
  - scikit-learn
  - pandas
  - matplotlib
  - astropy
  - numba
  - joblib
  - scikit-image
  # - pytest
  # - black 
  # - flake8
  # - mypy
  - tensorboard
  - tqdm
  - psutil
  - pip
  - pip:
    - setigen
    - blimpy
