# TODO: update to match current pipeline imports
name: etherscan
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - numpy=1.23.*
  - scikit-learn=1.3.*
  - pandas=2.0.*
  - matplotlib=3.7.*
  - astropy=5.3.*
  - numba=0.57.*
  - joblib=1.3.*
  - scikit-image=0.21.*
  - pytest=7.4.*
  - tensorboard=2.13.*
  - tqdm=4.65.*
  - psutil=5.9.*
  - h5py=3.9.*
  - scipy=1.11.*
  - nvidia::cuda-runtime=12.2.*
  - cudnn=8.9.*
  - jupyterlab
  - ipykernel
  - nb_conda_kernels
  - pip
  - pip:
    - tensorflow==2.16.*
    - setigen
    - blimpy
    - pyyaml
